return {
  nlp_plugin_id = 'com.nate.photographic.negative',

  nlp_metadata_fields = {
    'com.nate.photographic.negative.nlpConverted',
    'com.nate.photographic.negative.nlpVersion',
    'com.nate.photographic.negative.nlpSource',
    'com.nate.photographic.negative.nlpColorModel',
    'com.nate.photographic.negative.nlpPreSaturation',
    'com.nate.photographic.negative.nlpTones',
    'com.nate.photographic.negative.nlpColor',
    'com.nate.photographic.negative.nlpLUT',
    'com.nate.photographic.negative.rollName',
    'com.nate.photographic.negative.rollID',
    'com.nate.photographic.negative.nlpOriginalCameraMake',
    'com.nate.photographic.negative.nlpOriginalCameraModel',
    'com.nate.photographic.negative.nlpOriginalLensMake',
    'com.nate.photographic.negative.nlpOriginalLens',
    'com.nate.photographic.negative.nlpFilmStock',
    'com.nate.photographic.negative.nlpFilmISO',
    'com.nate.photographic.negative.nlpFilmFormatSize',
    'com.nate.photographic.negative.nlpShotAtIso',
    'com.nate.photographic.negative.nlpAperture',
    'com.nate.photographic.negative.nlpShutterSpeed',
    'com.nate.photographic.negative.nlpFocalLength',
    'com.nate.photographic.negative.nlpDateTaken',
    'com.nate.photographic.negative.nlpScanMethod',
    'com.nate.photographic.negative.nlpScanEquipment',
    'com.nate.photographic.negative.nlpScannerSoftware',
    'com.nate.photographic.negative.nlpLightSource',
    'com.nate.photographic.negative.nlpFilmHolder',
    'com.nate.photographic.negative.nlpFilmPushPull',
    'com.nate.photographic.negative.nlpDevelopedAt',
    'com.nate.photographic.negative.nlpDeveloper',
    'com.nate.photographic.negative.nlpDevDilution',
    'com.nate.photographic.negative.nlpDevTimeTemp',
    'com.nate.photographic.negative.nlpDevMethod',
    'com.nate.photographic.negative.nlpDevelopmentNotes',
  },
}
